version: '3'

services:
  db:
    container_name: hire_postgres
    image: postgres
    restart: always # always restart container when you restart docker itself.
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: hire_db
      POSTGRES_PASSWORD: hireapi
