version: "3"

services:
  api:
    container_name: api
    build: .
    volumes:
      - .:/user/src/app # real-time folder mapping
    ports:
      - 3000:3000
    command: yarn start:dev
    env_file:
      - .docker.development.env
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    env_file:
      - .docker.development.env
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
volumes:
  db-data:
